### ISSUE TITLE
How to run docker image with 'necrosis_to_background' as False?

### ISSUE THREAD

**Issue by ChoiDM** [NeuroAI-HD/HD-GLIO-AUTO#1]
Thank you for sharing your incredible work for free.

I want to extract tumor segmentation mask from brain MRI images.
The required mask type for me is not only contrast-enhanced and peri-tumoral but also necrosis.

In run.py script as given, the parameter 'necrosis_to_background' is set to True and
the result segmentation mask doesn't have necrosis class due to the default value.

How can I access the necrosis mask result on the provided docker image?
Thank you.

**Comment by FabianIsensee** [comment]
Hi there,
@jenspetersen can give you a proper response as to what this parameter does. 
I can only comment on the neural network underneath. This network does not predict necrosis at all, so there is no way of getting that. 
Best,
Fabian

**Comment by ChoiDM** [comment]
Thank you for answering.
I thought that I could gain necrosis mask by turning on the parameter.

Best,
Dong min.

**Comment by jenspetersen** [comment]
Hi, yeah, that's just there for when the network actually predicts necrosis, which isn't the case at the moment :)
