### ISSUE TITLE
Error occurs for large size images

### ISSUE THREAD

**Issue by ChoiDM** [NeuroAI-HD/HD-GLIO-AUTO#2]
Thank you for sharing your nice works.

While running on my docker environment, the error message below occurs only for large size images. (>100 MB, 1024x1024 px)

```
Image Exception : #22 :: Failed to read volume /output/FLAIR
Error : Error: short read, file may be truncated
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to read volume /output/FLAIR
Error : Error: short read, file may be truncated
Image Exception : #22 :: Failed to read volume /output/CT1
Error : Error: short read, file may be truncated
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to read volume /output/CT1
Error : Error: short read, file may be truncated
Aborted (core dumped)
Aborted (core dumped)
```
To decrease the input file size, I resampled the image to downscale the volume below 20 MB but it failed. 
Another trial was to increase the memory size of docker container by setting ```--memory 10G``` but it also not performed well.

I think the error occurs because the file size is too large for FSL to handle with.
Do you know any solution to tackle this problem?

Best,
Dongmin Choi.

**Comment by FabianIsensee** [comment]
@jenspetersen do you have an idea what could be going on?

**Comment by jenspetersen** [comment]
Never seen these errors, but a quick Google search suggests that there is an issue with your files. Can you try the fix proposed here https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;3ae9d96c.1902?

**Comment by ChoiDM** [comment]
Thank you for answering.
I will re-open this issue if it still generates the same problem after following the instruction that @jenspetersen linked.

Best,
Dongmin Choi.
